version: "3"

services:
  gun_chat:
    container_name: gun_chat
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:./
    ports:
      - 3000:3000

  gun:
    container_name: gun
    build:
      context: ./gun
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8765:8765