version: "3"

services:
  gun_chat:
    container_name: gun_chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3000

  relay:
    container_name: gun
    build:
      context: ./relay
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:8765