version: "3"

services:
  gun_chat:
    container_name: gun_chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - relay

  relay:
    container_name: relay
    build:
      context: ./relay
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8765:8765