version: "3"

services:
  gun-chat:
    container_name: gun-chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./chat/nginx.conf:/etc/nginx/nginx.conf
      - ./chat/examples:/var/www/html/examples
      - ./gun:/var/www/html/gun
    ports:
      - 3000:3000
    depends_on:
      - gun-relay

  gun-relay:
    container_name: gun-relay
    build:
      context: ./relay
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8765:8765